名字: 建筑
在:
  workflow_dispatch:
输入:
        package_name:
描述: “游戏包名称：”
必需: 真正的

工作:
建筑:
    runs-on: ubuntu-latest
步骤:
    - 用途: actions/checkout@v4
    - 用途: actions/setup-java@v4
与:
分布: 控制+空间触发自动完成。
        java-version: 11
贮存物: 使用突耳
    - 导航到下一个占位符。: |
跑'chmod+x./gradlewyou
我-我-我's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
我-我-我"s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
./gradlew:模块你喜欢吗
    - 用途: actions/upload-artifact@v4
与:
名字: zygisk-il2cppdumper
路径: out/magisk_module_release/
